services:
  proxy:
    image: nginx:latest
    ports: 
    - "80:80"
    networks:
    - frontend
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: notes
    networks:
      - backend
      - frontend
    depends_on:
    - mysql
    volumes:
    - web-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  mysql:
    image: mysql:latest
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notes
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
networks:
  frontend:
  backend:

volumes:
  mysql-data:
  web-logs: